-- Catalog Model V2 — schema/architecture changes only (no catalog data).
-- See docs/CATALOG_MODEL_V2.md for the full architectural writeup.
--
-- The CREATE TABLE / ALTER TABLE / ADD CONSTRAINT statements above the
-- trigger block at the bottom are auto-generated by `drizzle-kit generate`
-- from lib/db/schema/*.ts. The trigger block at the very bottom is explicit,
-- hand-written SQL (Drizzle can't express triggers) implementing the
-- point-3 canonical-release drift enforcement -- see its own comment.
--
-- Summary: new release_sources table; new product_releases columns
-- (edition_type, verification_status, production_status, status_checked_at)
-- + CHECK constraints; new products.canonical_release_id; item_number,
-- release_year, and chassis on product_releases and original_release_year on
-- products all become nullable (UNKNOWN > INVENTED for future catalog items);
-- the identity unique constraint gains NULLS NOT DISTINCT so nullable fields
-- can't defeat duplicate protection; and DB-level triggers that keep the
-- product compatibility columns permanently in sync with the canonical
-- release.
--
-- Not applied to Supabase in this pass.

CREATE TABLE "release_sources" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"release_id" uuid NOT NULL,
	"source_type" text NOT NULL,
	"source_url" text,
	"verified_fields" text[] DEFAULT '{}'::text[] NOT NULL,
	"checked_at" date,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "release_sources_source_type_check" CHECK ("release_sources"."source_type" in ('official_manufacturer', 'official_catalog_pdf', 'official_archive', 'trusted_secondary', 'other'))
);
--> statement-breakpoint
ALTER TABLE "release_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "product_releases" DROP CONSTRAINT "product_releases_identity_unique";--> statement-breakpoint
ALTER TABLE "product_releases" ALTER COLUMN "item_number" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product_releases" ALTER COLUMN "release_year" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product_releases" ALTER COLUMN "chassis" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "original_release_year" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product_releases" ADD COLUMN "edition_type" text DEFAULT 'other' NOT NULL;--> statement-breakpoint
ALTER TABLE "product_releases" ADD COLUMN "verification_status" text DEFAULT 'unverified' NOT NULL;--> statement-breakpoint
ALTER TABLE "product_releases" ADD COLUMN "production_status" text DEFAULT 'unknown' NOT NULL;--> statement-breakpoint
ALTER TABLE "product_releases" ADD COLUMN "status_checked_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "canonical_release_id" uuid;--> statement-breakpoint
ALTER TABLE "release_sources" ADD CONSTRAINT "release_sources_release_id_product_releases_id_fk" FOREIGN KEY ("release_id") REFERENCES "public"."product_releases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_release_sources_release" ON "release_sources" USING btree ("release_id");--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_canonical_release_id_product_releases_id_fk" FOREIGN KEY ("canonical_release_id") REFERENCES "public"."product_releases"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_products_canonical_release" ON "products" USING btree ("canonical_release_id");--> statement-breakpoint
ALTER TABLE "product_releases" ADD CONSTRAINT "product_releases_identity_unique" UNIQUE NULLS NOT DISTINCT("product_id","item_number","release_year","color");--> statement-breakpoint
ALTER TABLE "product_releases" ADD CONSTRAINT "product_releases_verification_status_check" CHECK ("product_releases"."verification_status" in ('verified', 'partial', 'unverified'));--> statement-breakpoint
ALTER TABLE "product_releases" ADD CONSTRAINT "product_releases_edition_type_check" CHECK ("product_releases"."edition_type" in ('original', 'premium', 'color_special', 'limited', 'anniversary', 'japan_cup', 'reissue', 'special', 'other'));--> statement-breakpoint
ALTER TABLE "product_releases" ADD CONSTRAINT "product_releases_production_status_check" CHECK ("product_releases"."production_status" in ('announced', 'active', 'discontinued', 'unknown'));--> statement-breakpoint
CREATE POLICY "release_sources_public_read" ON "release_sources" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);

-- =============================================================================
-- Catalog Model V2 hardening (point 3): DB-LEVEL enforcement that the three
-- Product compatibility/cache columns can NEVER drift from the canonical
-- release, even under a direct SQL edit after deploy (a future Catalog Admin,
-- a manual fix, a bulk import). Drizzle can't express triggers, so this is
-- explicit, documented SQL -- correctness of the architecture over "everything
-- must be generated". See docs/CATALOG_MODEL_V2.md section 3.
--
-- Three guarantees:
--   A. canonical_release_id, when set, must belong to the SAME product.
--   B. changing products.canonical_release_id re-syncs the three compat
--      columns from the NEW canonical release.
--   C. changing a canonical release's item_number/chassis/release_year
--      re-syncs its product's three compat columns automatically.
-- =============================================================================

-- (A) canonical_release_id must reference one of the product's own releases.
-- A plain FK can't express "same product", so this is a constraint trigger.
create or replace function trg_products_canonical_release_ownership()
returns trigger language plpgsql as $$
begin
  if new.canonical_release_id is not null then
    if not exists (
      select 1 from product_releases pr
      where pr.id = new.canonical_release_id and pr.product_id = new.id
    ) then
      raise exception 'canonical_release_id % does not belong to product %', new.canonical_release_id, new.id;
    end if;
  end if;
  return new;
end;
$$;

create constraint trigger products_canonical_release_ownership
  after insert or update of canonical_release_id on products
  deferrable initially deferred
  for each row execute function trg_products_canonical_release_ownership();

-- (B) When a product's canonical_release_id changes, pull the three compat
-- columns from the new canonical release (or NULL them if it's set to NULL).
create or replace function trg_products_sync_from_canonical()
returns trigger language plpgsql as $$
declare
  rel product_releases%rowtype;
begin
  if new.canonical_release_id is null then
    new.canonical_item_number := null;
    new.chassis := null;
    new.original_release_year := null;
  else
    select * into rel from product_releases where id = new.canonical_release_id;
    if found then
      new.canonical_item_number := rel.item_number;
      new.chassis := rel.chassis;
      new.original_release_year := rel.release_year;
    end if;
  end if;
  return new;
end;
$$;

create trigger products_sync_from_canonical
  before update of canonical_release_id on products
  for each row execute function trg_products_sync_from_canonical();

-- (C) When a canonical release's own item_number/chassis/release_year change,
-- re-sync the owning product's compat columns.
create or replace function trg_releases_sync_canonical_product()
returns trigger language plpgsql as $$
begin
  update products p
    set canonical_item_number = new.item_number,
        chassis = new.chassis,
        original_release_year = new.release_year
  where p.canonical_release_id = new.id;
  return new;
end;
$$;

create trigger releases_sync_canonical_product
  after update of item_number, chassis, release_year on product_releases
  for each row execute function trg_releases_sync_canonical_product();
