-- Catalog Model V2 — schema/architecture changes only (no data).
-- See docs/CATALOG_MODEL_V2.md for the full architectural writeup.
--
-- Auto-generated by `drizzle-kit generate` from lib/db/schema/*.ts (not
-- hand-written) — this is the canonical way schema DDL is produced in this
-- project; see docs/SUPABASE_SETUP.md.
--
-- Also includes `product_releases.item_number DROP NOT NULL`: this was
-- previously applied via a hand-written statement in the old, now-removed
-- 0006_catalog_integrity_corrections.sql, which changed the schema without
-- ever updating a tracked Drizzle snapshot. Folding it into this properly
-- snapshot-tracked migration corrects that gap rather than perpetuating it.
--
-- Summary of what this migration does:
--   - New table `release_sources` (persistent provenance for a release's
--     factual data — see docs/CATALOG_MODEL_V2.md section 13).
--   - New `product_releases` columns: `edition_type`, `verification_status`,
--     `production_status`, `status_checked_at` (+ their CHECK constraints).
--   - New `products.canonical_release_id` (nullable FK to
--     product_releases — UNKNOWN > INVENTED, never forced).
--   - `product_releases.item_number` becomes nullable (see above).
--
-- Does NOT touch any RLS policy from migrations 0000-0005, does not remove
-- any existing column, does not change any id. Idempotent in the sense that
-- every statement is additive (CREATE TABLE, ADD COLUMN, ADD CONSTRAINT) —
-- re-running this against a database that already has it applied will fail
-- loudly (column/table already exists) rather than silently duplicating
-- anything, which is the correct, safe behavior for schema DDL.

CREATE TABLE "release_sources" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"release_id" uuid NOT NULL,
	"source_type" text NOT NULL,
	"source_url" text,
	"verified_fields" text[] DEFAULT '{}'::text[] NOT NULL,
	"checked_at" date,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "release_sources_source_type_check" CHECK ("release_sources"."source_type" in ('official_manufacturer', 'official_catalog_pdf', 'official_archive', 'trusted_secondary', 'other'))
);
--> statement-breakpoint
ALTER TABLE "release_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "product_releases" ALTER COLUMN "item_number" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product_releases" ADD COLUMN "edition_type" text DEFAULT 'other' NOT NULL;--> statement-breakpoint
ALTER TABLE "product_releases" ADD COLUMN "verification_status" text DEFAULT 'unverified' NOT NULL;--> statement-breakpoint
ALTER TABLE "product_releases" ADD COLUMN "production_status" text DEFAULT 'unknown' NOT NULL;--> statement-breakpoint
ALTER TABLE "product_releases" ADD COLUMN "status_checked_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "canonical_release_id" uuid;--> statement-breakpoint
ALTER TABLE "release_sources" ADD CONSTRAINT "release_sources_release_id_product_releases_id_fk" FOREIGN KEY ("release_id") REFERENCES "public"."product_releases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_release_sources_release" ON "release_sources" USING btree ("release_id");--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_canonical_release_id_product_releases_id_fk" FOREIGN KEY ("canonical_release_id") REFERENCES "public"."product_releases"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_products_canonical_release" ON "products" USING btree ("canonical_release_id");--> statement-breakpoint
ALTER TABLE "product_releases" ADD CONSTRAINT "product_releases_verification_status_check" CHECK ("product_releases"."verification_status" in ('verified', 'partial', 'unverified'));--> statement-breakpoint
ALTER TABLE "product_releases" ADD CONSTRAINT "product_releases_edition_type_check" CHECK ("product_releases"."edition_type" in ('original', 'premium', 'color_special', 'limited', 'anniversary', 'japan_cup', 'reissue', 'special', 'other'));--> statement-breakpoint
ALTER TABLE "product_releases" ADD CONSTRAINT "product_releases_production_status_check" CHECK ("product_releases"."production_status" in ('announced', 'active', 'discontinued', 'unknown'));--> statement-breakpoint
CREATE POLICY "release_sources_public_read" ON "release_sources" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);