-- Catalog integrity pass: corrects already-deployed catalog rows in
-- place, preserving every primary key. See docs/CATALOG_AUDIT.md for
-- the full audit (every product/release, verification status, sources)
-- and lib/data/products.ts's file header + inline comments for the
-- reasoning behind each specific correction below. Generated by
-- scripts/generate-catalog-corrections.mjs (diffed from the pre-audit
-- snapshot -- not hand-written) EXCEPT the schema change and the
-- blanket JAN/MSRP clearing, which are unconditional (see their own
-- comments below) rather than diffed.
--
-- Does NOT touch migrations 0000-0005 or any RLS policy, and does not
-- change any id -- every statement below is a plain UPDATE against an
-- existing row (or one schema-widening ALTER COLUMN), never
-- INSERT/DELETE. Idempotent: re-running this sets the same values
-- again, harmlessly.


-- =========================================================================
-- 1. Schema: product_releases.item_number becomes nullable.
--
-- A release whose official Tamiya item number cannot be confidently
-- verified must store NULL, never a placeholder/sentinel string like
-- "UNVERIFIED" -- that would itself be fabricated catalog data, exactly
-- what this migration exists to stop doing. products.canonical_item_number
-- is already nullable (migration 0000) and needs no change here.
-- =========================================================================

alter table product_releases alter column item_number drop not null;


-- =========================================================================
-- 2. Unconditional: clear every release's barcode_jan, msrp_jpy, and
--    msrp_eur. None of this catalog's 60 releases has an officially
--    verified value for any of the three -- migration 0003's seed wrote
--    a deterministic PSEUDO-jan (now removed from lib/data/products.ts
--    entirely) and app-level ESTIMATED msrp figures (now clearly renamed
--    estimatedMsrpJPY in the seed source, kept out of the database on
--    purpose) into these factual columns. Both were demo/prototype data,
--    never real historical Tamiya figures -- they don't belong in the
--    database's source of truth. The demo market-pricing engine
--    (lib/data/market.ts, already labeled "demo" throughout its own UI)
--    continues to work from the in-app estimatedMsrpJPY figures directly,
--    not from these DB columns.
-- =========================================================================

update product_releases set barcode_jan = NULL, msrp_jpy = NULL, msrp_eur = NULL;


-- =========================================================================
-- 3. Corrected factual fields on already-deployed products, by id.
--    27 product row(s) affected.
-- =========================================================================

-- Aero Avante
update products set canonical_item_number = '18701', chassis = 'AR', description = 'The flagship of the AR chassis era, launched for Mini 4WD''s 30th anniversary. A low, wedge-shaped aero body that became the face of modern Mini 4WD racing.' where id = 'c8132bd5-23ee-5f36-b3f6-a75ef0c27ea3';

-- Raikiri
update products set canonical_item_number = '18640', chassis = 'MA' where id = 'c7a440cc-dc07-5ecc-bae3-c2770dc8b66e';

-- DCR-01
update products set canonical_item_number = '18646' where id = 'd341ec22-c1f9-5a03-906d-444f8eee5401';

-- Geo Glider
update products set canonical_item_number = '18716', original_release_year = 2018 where id = '68acb096-f01b-55b2-949b-a959279a2fa5';

-- Shadow Shark
update products set canonical_item_number = '18704', chassis = 'AR', description = 'Sharp predatory silhouette debuting on the aerodynamic, responsive AR chassis.' where id = '6f41e40f-a48e-509f-8602-dfd303e25795';

-- Festa Jaune
update products set canonical_item_number = '18637', chassis = 'MA', description = 'Bright competition body on the MA chassis, popular for its clean lines and rigidity.', original_release_year = 2014 where id = '51deac9c-f8a7-5eff-984f-968d6ad88659';

-- Neo-Tridagger ZMC
update products set canonical_item_number = '19409', chassis = 'Super 1' where id = '9793fbe8-dcf7-51c9-9f45-185194a0bc92';

-- Victory Magnum
update products set canonical_item_number = '19406' where id = 'f603ed6f-e601-5372-9fe7-6fd1034b6065';

-- Cyclone Magnum
update products set canonical_item_number = '19412' where id = '53791485-2948-5176-8acb-2ec947eafc51';

-- Beat Magnum
update products set canonical_item_number = '19421' where id = 'a66d871c-00b1-56e5-9bc4-1621ea1729b2';

-- Hurricane Sonic
update products set canonical_item_number = '19415' where id = 'dee35418-283b-5603-889b-b3eb2d68eea5';

-- Buster Sonic
update products set canonical_item_number = '19423' where id = 'da28c703-24ef-5ebd-a952-87346735dc7e';

-- Avante
update products set canonical_item_number = '18014' where id = '82b478fd-21dd-5c93-82fb-bf50461a107d';

-- Avante Mk.II
update products set canonical_item_number = '18614', chassis = 'MS', description = 'The MS-chassis Avante Mk.II, Mini 4WD PRO Series No.14 -- a modern take on the Avante line, not the vintage original.', original_release_year = 2006, rarity = 'Uncommon' where id = '6dcb6511-5277-561f-a880-95ef828ce44f';

-- Super Avante
update products set canonical_item_number = '18101' where id = 'dcd372ac-5ad2-5a70-ae48-f1c4a6d6de4a';

-- Vanguard Sonic
update products set canonical_item_number = '19407', original_release_year = 1995 where id = 'a00d2b12-6a67-56ee-8db5-392eaf86d5c7';

-- Great Emperor
update products set canonical_item_number = '18036' where id = '203f8219-9d37-5a1a-aad6-9437c80a1ea8';

-- Proto Emperor ZX
update products set canonical_item_number = '18038' where id = 'a1fd4f6d-0834-5f09-ac3c-5d4b398f0968';

-- Dash-2 Burning Sun
update products set canonical_item_number = '18015' where id = '3b443635-b33f-5553-a39d-eba8b8cafddb';

-- Dash-3 Shooting Star
update products set canonical_item_number = '18019' where id = '4b53383c-c417-53c6-addb-e87126546d89';

-- Dash-4 Cannon Ball
update products set canonical_item_number = NULL where id = 'd2c3e3d8-050d-5b9b-932f-023f2ee7dce2';

-- Astute
update products set canonical_item_number = NULL where id = 'be48e786-11c6-567f-b063-8026957bb403';

-- Dash-01 Horizon
update products set canonical_item_number = NULL where id = '813a9ba0-170e-5636-9a9a-a7e7fca32366';

-- Dyna-Hawk GX
update products set canonical_item_number = '19201' where id = 'd3b4ad34-05ac-592e-ad93-fab4cfde0a5a';

-- Mad Bull
update products set canonical_item_number = NULL where id = '643f208f-c8f6-5574-b9cf-565e28602d17';

-- Trigale
update products set canonical_item_number = '18638' where id = 'b972592b-ce68-5f39-b3a1-cdc8984d3817';

-- Thunder Shot
update products set canonical_item_number = NULL where id = '059b5b3f-9ee9-5932-b39f-879642b9414c';


-- =========================================================================
-- 4. Corrected factual fields on already-deployed releases, by id.
--    47 release row(s) affected.
-- =========================================================================

-- Aero Avante
update product_releases set item_number = '18701', chassis = 'AR' where id = 'a2baec17-32b5-5ca7-996b-4cdc2da725ba';

-- Aero Avante Clear Body (Polycarbonate)
update product_releases set item_number = '18701', chassis = 'AR' where id = '107f030c-2b39-5659-8c00-ae11bd2a86d4';

-- Aero Avante Black Special
update product_releases set item_number = '18701', chassis = 'AR' where id = '21b0cb0d-bb39-51ff-a5e6-df45c3245372';

-- Raikiri
update product_releases set item_number = '18640', chassis = 'MA' where id = '9a415521-3094-5724-a26b-e42a2c0148fa';

-- Raikiri Black Special
update product_releases set item_number = '18640', chassis = 'MA' where id = '5addae7a-e863-5cfe-8231-7af05fcfcbb6';

-- DCR-01
update product_releases set item_number = '18646' where id = 'd32c3468-4ce4-5968-ba4e-d1e47e30eb01';

-- Geo Glider
update product_releases set item_number = '18716', release_year = 2018 where id = 'a9a18e0d-7aa2-5481-94b6-ebc670daaa55';

-- Shadow Shark
update product_releases set item_number = '18704', chassis = 'AR' where id = 'b57fbc18-d57c-5b3c-9def-ffb4e70c9e27';

-- Festa Jaune
update product_releases set item_number = '18637', chassis = 'MA', release_year = 2014 where id = 'cbd6e611-e421-5c10-bbd3-352beb80f6fc';

-- Neo-Tridagger ZMC
update product_releases set item_number = '19409', chassis = 'Super 1' where id = 'fcaf3f82-93b5-5a52-8087-c96e771a030c';

-- Neo-Tridagger ZMC (Premium)
update product_releases set item_number = '19409' where id = '73dcd8e6-82ab-54c4-961b-f4132bf6d638';

-- Magnum Saber Premium
update product_releases set item_number = '19431', chassis = 'Super II' where id = '0fdbfd56-f257-5b84-b541-e08a7450cc34';

-- Sonic Saber Premium
update product_releases set item_number = '19432', chassis = 'Super II', release_year = 2011 where id = '62cca367-8a73-5280-b2a2-0aa9497d093d';

-- Victory Magnum
update product_releases set item_number = '19406' where id = '6ed25d50-4099-5924-b7e5-d7a21945a3f6';

-- Victory Magnum Premium
update product_releases set item_number = '19434', chassis = 'Super II', release_year = 2011, release_date = '2011-06-25' where id = '0bdb9bcd-e4aa-53ab-b004-984cae96fdca';

-- Cyclone Magnum
update product_releases set item_number = '19412' where id = 'efd6902b-f080-5165-8a13-0375c1d32298';

-- Cyclone Magnum Premium
update product_releases set item_number = '19440', chassis = 'AR', release_year = 2014, release_date = '2014-11-21' where id = '85a3549a-d563-5dda-bc6d-bd1ac684601e';

-- Beat Magnum
update product_releases set item_number = '19421' where id = '7683c862-f484-5603-aa28-c76ae7453892';

-- Beat Magnum Premium
update product_releases set item_number = '19444', chassis = 'AR', release_year = 2015, release_date = '2015-03-21' where id = 'a49b33d9-9f2c-5333-9521-8a7c732995d2';

-- Hurricane Sonic
update product_releases set item_number = '19415' where id = '71addadb-04b3-579f-96f2-c5e976cf1cd5';

-- Hurricane Sonic Premium
update product_releases set item_number = '19415', chassis = 'AR' where id = 'e1b626f8-e0ea-52c9-86f0-eb870561d70d';

-- Buster Sonic
update product_releases set item_number = '19423' where id = '217fd7d2-2090-593c-bb7d-bef7ce1cf154';

-- Avante Jr.
update product_releases set item_number = '18014', chassis = 'Type 2', notes = 'Original ''Avante Jr.'' on the Type 2 chassis.' where id = 'cafbb6ca-1aba-5732-946d-0045d054aa5c';

-- Avante (Premium)
update product_releases set item_number = '18014' where id = '7f3f7461-0dee-5d6a-b99d-36e2d910f0ef';

-- Avante Mk.II
update product_releases set item_number = '18614', chassis = 'MS', release_year = 2006, release_date = '2006-06-24', discontinued = false where id = '5a123617-c84c-5012-ab20-1a9d493259e0';

-- Super Avante
update product_releases set item_number = '18101' where id = '5e5251c2-a130-5fb0-93a7-2bd73c63736d';

-- Vanguard Sonic
update product_releases set item_number = '19407', release_year = 1995 where id = '203f1f0f-1f5d-5e3b-bd56-b1a175f3e121';

-- Vanguard Sonic (Super II)
update product_releases set item_number = '19435' where id = 'b3639c7d-581e-5da8-9ec4-ea1eb9d61193';

-- Dash-1 Emperor Premium
update product_releases set item_number = '18025' where id = 'f576fa21-8e57-5fa0-953e-f468653e3767';

-- Dash-1 Emperor (2026 Reissue)
update product_releases set chassis = 'Type 3', notes = 'Modern sealed reissue sharing the classic 18025 item number and Type 3 chassis.' where id = '79e32904-fe5d-5d30-bf54-8643ce4b42d3';

-- Great Emperor
update product_releases set item_number = '18036' where id = '8c2ca80b-8a9d-5b7a-9325-aec13a0db9ba';

-- Great Emperor Premium
update product_releases set item_number = '18075' where id = '532f8e3a-f55f-5936-abcd-58e0f8538785';

-- Proto Emperor ZX
update product_releases set item_number = '18038' where id = '4d5b0a9a-498f-51fc-accd-9316ca11c843';

-- Proto Emperor ZX Premium (Black Special)
update product_releases set item_number = '95450' where id = 'f0614cb8-d0cb-521d-aa2c-4fc304f39430';

-- Dash-2 Burning Sun
update product_releases set item_number = '18015' where id = '1d677e65-ca9c-5549-94c5-32e9b957b31a';

-- Dash-3 Shooting Star
update product_releases set item_number = '18019' where id = '178ef6b8-594c-5cf4-8084-3c910576b29b';

-- Dash-4 Cannon Ball
update product_releases set item_number = NULL where id = 'c63b8f4a-43f3-597b-82e5-f0e45bb45b7a';

-- Astute
update product_releases set item_number = NULL where id = '3d1c1580-c921-530f-9aaf-7ca5ff77e86c';

-- Astute (Reissue)
update product_releases set item_number = NULL where id = '96deae1d-dfec-5aaf-a247-835386533002';

-- Dash-01 Horizon
update product_releases set item_number = NULL where id = 'a0b042ac-7e6c-57f4-98a2-bd92e8e39f39';

-- Dyna-Hawk GX
update product_releases set item_number = '19201' where id = '2af882f6-8c66-5508-9acd-2240aac287ad';

-- Dyna-Hawk GX Premium
update product_releases set item_number = '19201' where id = '1ede5023-9035-5342-b207-6242c5f5190a';

-- Mad Bull
update product_releases set item_number = NULL where id = '454a8d07-e963-5699-9a8c-2151917f75a5';

-- Mad Bull (2013 Reissue)
update product_releases set item_number = NULL where id = 'eb3b81bb-3a11-56af-a0cf-b625a1501434';

-- Trigale
update product_releases set item_number = '18638' where id = '08b3cc73-8c45-5ddd-bab4-9167c7f93c41';

-- Thunder Shot (Type 3)
update product_releases set item_number = NULL where id = 'dcaa9d00-fe3f-5bc4-9bfa-5bc1078e2087';

-- Thunder Shot Premium
update product_releases set item_number = NULL where id = 'f4e3f6b8-8ce6-5b87-9d94-5f64a24c031a';
