-- Catalog integrity pass: corrects already-deployed catalog rows in
-- place, preserving every primary key. See docs/CATALOG_AUDIT.md for
-- the full audit (every product/release, verification status, sources)
-- and lib/data/products.ts's file header + inline comments for the
-- reasoning behind each specific correction below. Generated by
-- scripts/generate-catalog-corrections.mjs (diffed from the pre-audit
-- snapshot -- not hand-written) EXCEPT the schema change and the
-- blanket JAN/MSRP clearing, which are unconditional (see their own
-- comments below) rather than diffed.
--
-- Does NOT touch migrations 0000-0005 or any RLS policy, and does not
-- change any id -- every statement below is a plain UPDATE against an
-- existing row (or one schema-widening ALTER COLUMN), never
-- INSERT/DELETE. Idempotent: re-running this sets the same values
-- again, harmlessly.


-- =========================================================================
-- 1. Schema: product_releases.item_number becomes nullable.
--
-- A release whose official Tamiya item number cannot be confidently
-- verified must store NULL, never a placeholder/sentinel string like
-- "UNVERIFIED" -- that would itself be fabricated catalog data, exactly
-- what this migration exists to stop doing. products.canonical_item_number
-- is already nullable (migration 0000) and needs no change here.
-- =========================================================================

alter table product_releases alter column item_number drop not null;


-- =========================================================================
-- 2. Unconditional: clear every release's barcode_jan, msrp_jpy, and
--    msrp_eur. None of this catalog's 60 releases has an officially
--    verified value for any of the three -- migration 0003's seed wrote
--    a deterministic PSEUDO-jan (now removed from lib/data/products.ts
--    entirely) and app-level ESTIMATED msrp figures (now clearly renamed
--    estimatedMsrpJPY in the seed source, kept out of the database on
--    purpose) into these factual columns. Both were demo/prototype data,
--    never real historical Tamiya figures -- they don't belong in the
--    database's source of truth. The demo market-pricing engine
--    (lib/data/market.ts, already labeled "demo" throughout its own UI)
--    continues to work from the in-app estimatedMsrpJPY figures directly,
--    not from these DB columns.
-- =========================================================================

update product_releases set barcode_jan = NULL, msrp_jpy = NULL, msrp_eur = NULL;


-- =========================================================================
-- 3. Corrected factual fields on already-deployed products, by id.
--    9 product row(s) affected.
-- =========================================================================

-- Aero Avante
update products set canonical_item_number = '18701', chassis = 'AR', description = 'The flagship of the AR chassis era, launched for Mini 4WD''s 30th anniversary. A low, wedge-shaped aero body that became the face of modern Mini 4WD racing.' where id = 'c8132bd5-23ee-5f36-b3f6-a75ef0c27ea3';

-- Raikiri
update products set canonical_item_number = '18640', chassis = 'MA' where id = 'c7a440cc-dc07-5ecc-bae3-c2770dc8b66e';

-- DCR-01
update products set canonical_item_number = '18646' where id = 'd341ec22-c1f9-5a03-906d-444f8eee5401';

-- Geo Glider
update products set canonical_item_number = '18716' where id = '68acb096-f01b-55b2-949b-a959279a2fa5';

-- Shadow Shark
update products set canonical_item_number = '18704', chassis = 'AR', description = 'Sharp predatory silhouette debuting on the aerodynamic, responsive AR chassis.' where id = '6f41e40f-a48e-509f-8602-dfd303e25795';

-- Avante Mk.II
update products set canonical_item_number = NULL where id = '6dcb6511-5277-561f-a880-95ef828ce44f';

-- Super Avante
update products set canonical_item_number = '18101' where id = 'dcd372ac-5ad2-5a70-ae48-f1c4a6d6de4a';

-- Dash-4 Cannon Ball
update products set canonical_item_number = NULL where id = 'd2c3e3d8-050d-5b9b-932f-023f2ee7dce2';

-- Thunder Shot
update products set canonical_item_number = NULL where id = '059b5b3f-9ee9-5932-b39f-879642b9414c';


-- =========================================================================
-- 4. Corrected factual fields on already-deployed releases, by id.
--    15 release row(s) affected.
-- =========================================================================

-- Aero Avante
update product_releases set item_number = '18701', chassis = 'AR' where id = 'a2baec17-32b5-5ca7-996b-4cdc2da725ba';

-- Aero Avante Clear Body (Polycarbonate)
update product_releases set item_number = '18701', chassis = 'AR' where id = '107f030c-2b39-5659-8c00-ae11bd2a86d4';

-- Aero Avante Black Special
update product_releases set item_number = '18701', chassis = 'AR' where id = '21b0cb0d-bb39-51ff-a5e6-df45c3245372';

-- Raikiri
update product_releases set item_number = '18640', chassis = 'MA' where id = '9a415521-3094-5724-a26b-e42a2c0148fa';

-- Raikiri Black Special
update product_releases set item_number = '18640', chassis = 'MA' where id = '5addae7a-e863-5cfe-8231-7af05fcfcbb6';

-- DCR-01
update product_releases set item_number = '18646' where id = 'd32c3468-4ce4-5968-ba4e-d1e47e30eb01';

-- Geo Glider
update product_releases set item_number = '18716' where id = 'a9a18e0d-7aa2-5481-94b6-ebc670daaa55';

-- Shadow Shark
update product_releases set item_number = '18704', chassis = 'AR' where id = 'b57fbc18-d57c-5b3c-9def-ffb4e70c9e27';

-- Magnum Saber Premium
update product_releases set item_number = '19431', chassis = 'Super II' where id = '0fdbfd56-f257-5b84-b541-e08a7450cc34';

-- Avante Mk.II
update product_releases set item_number = NULL where id = '5a123617-c84c-5012-ab20-1a9d493259e0';

-- Super Avante
update product_releases set item_number = '18101' where id = '5e5251c2-a130-5fb0-93a7-2bd73c63736d';

-- Dash-1 Emperor (2026 Reissue)
update product_releases set chassis = 'Type 3', notes = 'Modern sealed reissue sharing the classic 18025 item number and Type 3 chassis.' where id = '79e32904-fe5d-5d30-bf54-8643ce4b42d3';

-- Dash-4 Cannon Ball
update product_releases set item_number = NULL where id = 'c63b8f4a-43f3-597b-82e5-f0e45bb45b7a';

-- Thunder Shot (Type 3)
update product_releases set item_number = NULL where id = 'dcaa9d00-fe3f-5bc4-9bfa-5bc1078e2087';

-- Thunder Shot Premium
update product_releases set item_number = NULL where id = 'f4e3f6b8-8ce6-5b87-9d94-5f64a24c031a';
