-- Catalog Model V2 — normalizes the existing catalog into the new
-- architecture. See docs/CATALOG_MODEL_V2.md for the full writeup and
-- docs/CATALOG_AUDIT.md for the underlying factual audit this migration
-- carries forward (this migration ABSORBS what the old, now-removed
-- 0006_catalog_integrity_corrections.sql did -- factual item/chassis/
-- year corrections, pseudo-JAN removal, demo-MSRP removal -- plus the
-- new V2-specific normalization: canonical_release_id, verification
-- status, edition type, production status, and provenance).
--
-- Generated by scripts/generate-catalog-normalization.mjs as a FULL
-- SYNC from lib/data/products.ts (not a diff) -- every UPDATE below
-- targets an existing row by id; every value comes directly from the
-- current seed, so this migration can never drift from it. Requires
-- migration 0006_catalog_model_v2.sql (schema) to already be applied.
--
-- Idempotent: every statement sets the same values again on a re-run,
-- harmlessly, except the two INSERT blocks (new releases, sources),
-- which use `on conflict (id) do nothing`.


-- =========================================================================
-- 1. Unconditional: clear barcode_jan/msrp_jpy/msrp_eur for every release.
--    No release in this catalog has a verified real JAN or MSRP as of
--    this pass -- see lib/data/products.ts's file header, point 2, and
--    lib/types.ts's estimatedMsrpJPY/EUR split (the demo estimate NEVER
--    reaches these factual columns).
-- =========================================================================

update product_releases set barcode_jan = NULL, msrp_jpy = NULL, msrp_eur = NULL;


-- =========================================================================
-- 2. Full sync: every product's factual fields, by id.
--    36 product row(s).
-- =========================================================================

-- Aero Avante
update products set canonical_item_number = '18701', chassis = 'AR', description = 'The flagship of the AR chassis era, launched for Mini 4WD''s 30th anniversary. A low, wedge-shaped aero body that became the face of modern Mini 4WD racing.', original_release_year = 2012, rarity = 'Common' where id = 'c8132bd5-23ee-5f36-b3f6-a75ef0c27ea3';

-- Aero Avante Japan Cup 2013
update products set canonical_item_number = '18718', chassis = 'MA', description = 'Japan Cup commemorative colourway of the Aero Avante. Event-limited and hard to find.', original_release_year = 2013, rarity = 'Very Rare' where id = '07cc02e9-2626-5a60-92fb-2c2ed2402d7f';

-- Astute
update products set canonical_item_number = NULL, chassis = 'Super 1', description = 'Sharp-nosed Super Mini 4WD icon, a competitive favourite of the early 90s.', original_release_year = 1992, rarity = 'Uncommon' where id = 'be48e786-11c6-567f-b063-8026957bb403';

-- Avante
update products set canonical_item_number = '18014', chassis = 'Type 2', description = 'The original wedge that started the Avante dynasty, reissued for the Super II chassis.', original_release_year = 1988, rarity = 'Uncommon' where id = '82b478fd-21dd-5c93-82fb-bf50461a107d';

-- Avante Mk.II
update products set canonical_item_number = '18614', chassis = 'MS', description = 'The MS-chassis Avante Mk.II, Mini 4WD PRO Series No.14 -- a modern take on the Avante line, not the vintage original.', original_release_year = 2006, rarity = 'Uncommon' where id = '6dcb6511-5277-561f-a880-95ef828ce44f';

-- Beat Magnum
update products set canonical_item_number = '19421', chassis = 'Super TZ', description = 'The final Magnum of the original manga arc. Iconic red-and-white split cowl.', original_release_year = 1997, rarity = 'Rare' where id = 'a66d871c-00b1-56e5-9bc4-1621ea1729b2';

-- Buster Sonic
update products set canonical_item_number = '19423', chassis = 'Super TZ', description = 'The last Sonic of the arc, paired with the Beat Magnum in the series finale.', original_release_year = 1997, rarity = 'Rare' where id = 'da28c703-24ef-5ebd-a952-87346735dc7e';

-- Copperfang
update products set canonical_item_number = '18092', chassis = 'FM-A', description = 'Front-motor FM-A machine with a low, fang-shaped nose for downforce.', original_release_year = 2019, rarity = 'Uncommon' where id = 'e2f47ba4-03f1-5adb-8252-471c76729292';

-- Cyclone Magnum
update products set canonical_item_number = '19412', chassis = 'Super TZ', description = 'Twin-intake cowl on the high-rigidity Super TZ chassis. One of the most beloved Magnum forms.', original_release_year = 1996, rarity = 'Uncommon' where id = '53791485-2948-5176-8acb-2ec947eafc51';

-- Dash-01 Horizon
update products set canonical_item_number = NULL, chassis = 'Super II', description = 'Wing-heavy competition body reissued for the modern Super II chassis.', original_release_year = 2017, rarity = 'Rare' where id = '813a9ba0-170e-5636-9a9a-a7e7fca32366';

-- Dash-1 Emperor
update products set canonical_item_number = '18025', chassis = 'Type 3', description = 'The legendary Emperor. Star machine of the Dash! Yonkuro manga and a cornerstone of any vintage-minded collection. First released in 1990 and reissued several times since.', original_release_year = 1990, rarity = 'Rare' where id = '2972e27d-7c75-5534-9ed4-1603ef4a6655';

-- Dash-2 Burning Sun
update products set canonical_item_number = '18015', chassis = 'Type 1', description = 'Vintage Type 1 rival machine from the Dash! Yonkuro era. Extremely collectible in sealed condition.', original_release_year = 1989, rarity = 'Grail' where id = '3b443635-b33f-5553-a39d-eba8b8cafddb';

-- Dash-3 Shooting Star
update products set canonical_item_number = '18019', chassis = 'Type 3', description = 'The high-speed Shooting Star on the Type 3 chassis. A classic of the first Mini 4WD boom.', original_release_year = 1989, rarity = 'Very Rare' where id = '4b53383c-c417-53c6-addb-e87126546d89';

-- Dash-4 Cannon Ball
update products set canonical_item_number = NULL, chassis = 'Type 3', description = 'Heavy-hitting Cannon Ball, rounding out the Dash brothers lineup.', original_release_year = 1990, rarity = 'Very Rare' where id = 'd2c3e3d8-050d-5b9b-932f-023f2ee7dce2';

-- DCR-01
update products set canonical_item_number = '18646', chassis = 'MA', description = 'Dual Ridge cowl developed with real aerodynamic testing. Successor lineage to the Avante family.', original_release_year = 2018, rarity = 'Common' where id = 'd341ec22-c1f9-5a03-906d-444f8eee5401';

-- Dyna-Hawk GX
update products set canonical_item_number = '19201', chassis = 'Super X', description = 'MAX GP machine with a distinctive hawk canopy. A late-90s standout.', original_release_year = 1998, rarity = 'Rare' where id = 'd3b4ad34-05ac-592e-ad93-fab4cfde0a5a';

-- Emperor (Premium Black Special)
update products set canonical_item_number = '18717', chassis = 'AR', description = 'Blacked-out AR-chassis Emperor special. A limited run prized by Emperor collectors.', original_release_year = 2017, rarity = 'Very Rare' where id = '6d6174e7-4040-5035-a3a4-cede97265d38';

-- Festa Jaune
update products set canonical_item_number = '18637', chassis = 'MA', description = 'Bright competition body on the MA chassis, popular for its clean lines and rigidity.', original_release_year = 2014, rarity = 'Uncommon' where id = '51deac9c-f8a7-5eff-984f-968d6ad88659';

-- Fire Dragon
update products set canonical_item_number = '19414', chassis = 'Super 1', description = 'Dragon-themed Super Mini 4WD from the classic Dragon series.', original_release_year = 1992, rarity = 'Uncommon' where id = '65c7f3e3-ebfc-55a6-8855-c0c495164b72';

-- Geo Glider
update products set canonical_item_number = '18716', chassis = 'FM-A', description = 'Front-motor FM-A chassis machine with a smooth gliding profile tuned for stability on technical sections.', original_release_year = 2018, rarity = 'Uncommon' where id = '68acb096-f01b-55b2-949b-a959279a2fa5';

-- Great Emperor
update products set canonical_item_number = '18036', chassis = 'Type 3', description = 'The upgraded Emperor with a more aggressive cowl. Highly sought after in original form.', original_release_year = 1990, rarity = 'Very Rare' where id = '203f8219-9d37-5a1a-aad6-9437c80a1ea8';

-- Hurricane Sonic
update products set canonical_item_number = '19415', chassis = 'Super TZ', description = 'Sonic lineage''s high-speed form with sweeping intakes on the Super TZ chassis.', original_release_year = 1996, rarity = 'Uncommon' where id = 'dee35418-283b-5603-889b-b3eb2d68eea5';

-- Mad Bull
update products set canonical_item_number = NULL, chassis = 'Super II', description = 'Bull-nosed off-road styling, a friendly entry point on the Super II chassis.', original_release_year = 1998, rarity = 'Common' where id = '643f208f-c8f6-5574-b9cf-565e28602d17';

-- Magnum Saber
update products set canonical_item_number = '19401', chassis = 'Super 1', description = 'Go Seiba''s first machine and the icon that launched the Fully Cowled boom of the 90s.', original_release_year = 1994, rarity = 'Rare' where id = 'fa551244-1a12-54ec-b937-ad1b5603e8bb';

-- Manta Ray
update products set canonical_item_number = '19413', chassis = 'Super 1', description = 'Wide, low manta-inspired body. One of the most recognisable Super Mini 4WD machines.', original_release_year = 1991, rarity = 'Uncommon' where id = '0b2e1cf8-6c19-5342-89ef-6a53b3f51af3';

-- Neo-Tridagger ZMC
update products set canonical_item_number = '19409', chassis = 'Super 1', description = 'The ZMC ''Zero Material Carbon'' hero machine. A fan favourite reissued for the modern Super II chassis.', original_release_year = 1998, rarity = 'Rare' where id = '9793fbe8-dcf7-51c9-9f45-185194a0bc92';

-- Proto Emperor ZX
update products set canonical_item_number = '18038', chassis = 'Super II', description = 'The prototype Emperor, a fan-favourite variant of the Emperor bloodline.', original_release_year = 2016, rarity = 'Rare' where id = 'a1fd4f6d-0834-5f09-ac3c-5d4b398f0968';

-- Raikiri
update products set canonical_item_number = '18640', chassis = 'MA', description = 'Aggressive twin-blade styling on the rigid AR chassis. A staple of the modern competitive scene.', original_release_year = 2014, rarity = 'Common' where id = 'c7a440cc-dc07-5ecc-bae3-c2770dc8b66e';

-- Shadow Shark
update products set canonical_item_number = '18704', chassis = 'AR', description = 'Sharp predatory silhouette debuting on the aerodynamic, responsive AR chassis.', original_release_year = 2020, rarity = 'Uncommon' where id = '6f41e40f-a48e-509f-8602-dfd303e25795';

-- Sonic Saber
update products set canonical_item_number = '19402', chassis = 'Super 1', description = 'Retsu Seiba''s counterpart to the Magnum. Sleek blue styling built for cornering.', original_release_year = 1994, rarity = 'Rare' where id = '896cc70e-3048-594d-9389-cb9808a5ad53';

-- Super Avante
update products set canonical_item_number = '18101', chassis = 'VZ', description = 'A modern reinterpretation of the Avante line on the lightweight VZ chassis.', original_release_year = 2020, rarity = 'Common' where id = 'dcd372ac-5ad2-5a70-ae48-f1c4a6d6de4a';

-- Sword Flash
update products set canonical_item_number = '18091', chassis = 'VZ', description = 'Blade-like VZ chassis body tuned for light, nimble handling.', original_release_year = 2020, rarity = 'Common' where id = '5b415a05-bc7c-589c-8b9c-3b3806479f6b';

-- Thunder Shot
update products set canonical_item_number = NULL, chassis = 'Type 3', description = 'First-boom classic with a bold canopy. Reissued periodically as a nostalgia piece.', original_release_year = 1988, rarity = 'Rare' where id = '059b5b3f-9ee9-5932-b39f-879642b9414c';

-- Trigale
update products set canonical_item_number = '18638', chassis = 'AR', description = 'Angular AR-chassis competition machine with a purposeful stance.', original_release_year = 2015, rarity = 'Uncommon' where id = 'b972592b-ce68-5f39-b3a1-cdc8984d3817';

-- Vanguard Sonic
update products set canonical_item_number = '19407', chassis = 'Super 1', description = 'MAX GP hero machine reissued on Super II. Smooth, purposeful racing body.', original_release_year = 1995, rarity = 'Uncommon' where id = 'a00d2b12-6a67-56ee-8db5-392eaf86d5c7';

-- Victory Magnum
update products set canonical_item_number = '19406', chassis = 'Super 1', description = 'The Magnum''s evolution with a more aggressive cowl. A defining silhouette of the series.', original_release_year = 1995, rarity = 'Uncommon' where id = 'f603ed6f-e601-5372-9fe7-6fd1034b6065';


-- =========================================================================
-- 3. Full sync: every already-deployed release's factual + Catalog Model
--    V2 fields, by id.
--    60 release row(s).
-- =========================================================================

-- Aero Avante -- Aero Avante
update product_releases set item_number = '18701', chassis = 'AR', edition_name = 'Aero Avante', release_type = 'Original', edition_type = 'original', release_year = 2012, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'a2baec17-32b5-5ca7-996b-4cdc2da725ba';

-- Aero Avante -- Aero Avante Clear Body (Polycarbonate)
update product_releases set item_number = '18701', chassis = 'AR', edition_name = 'Aero Avante Clear Body (Polycarbonate)', release_type = 'Clear Body', edition_type = 'color_special', release_year = 2013, release_date = NULL, notes = 'Lightweight polycarbonate special.', discontinued = false, rarity = 'Uncommon', verification_status = 'partial', production_status = 'unknown', status_checked_at = NULL where id = '107f030c-2b39-5659-8c00-ae11bd2a86d4';

-- Aero Avante -- Aero Avante Black Special
update product_releases set item_number = '18701', chassis = 'AR', edition_name = 'Aero Avante Black Special', release_type = 'Color Special', edition_type = 'color_special', release_year = 2014, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Uncommon', verification_status = 'partial', production_status = 'unknown', status_checked_at = NULL where id = '21b0cb0d-bb39-51ff-a5e6-df45c3245372';

-- Aero Avante Japan Cup 2013 -- Aero Avante Japan Cup 2013
update product_releases set item_number = '18718', chassis = 'MA', edition_name = 'Aero Avante Japan Cup 2013', release_type = 'Japan Cup Edition', edition_type = 'original', release_year = 2013, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '035abf4d-65da-5b0c-855d-9e611798c4e4';

-- Astute -- Astute
update product_releases set item_number = NULL, chassis = 'Super 1', edition_name = 'Astute', release_type = 'Original', edition_type = 'original', release_year = 1992, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Rare', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '3d1c1580-c921-530f-9aaf-7ca5ff77e86c';

-- Astute -- Astute (Reissue)
update product_releases set item_number = NULL, chassis = 'Super 1', edition_name = 'Astute (Reissue)', release_type = 'Reissue', edition_type = 'reissue', release_year = 2015, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '96deae1d-dfec-5aaf-a247-835386533002';

-- Avante -- Avante Jr.
update product_releases set item_number = '18014', chassis = 'Type 2', edition_name = 'Avante Jr.', release_type = 'Original', edition_type = 'original', release_year = 1988, release_date = NULL, notes = 'Original ''Avante Jr.'' on the Type 2 chassis.', discontinued = false, rarity = 'Very Rare', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'cafbb6ca-1aba-5732-946d-0045d054aa5c';

-- Avante -- Avante (Premium)
update product_releases set item_number = NULL, chassis = 'Super II', edition_name = 'Avante (Premium)', release_type = 'Premium', edition_type = 'premium', release_year = 2011, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Uncommon', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '7f3f7461-0dee-5d6a-b99d-36e2d910f0ef';

-- Avante Mk.II -- Avante Mk.II
update product_releases set item_number = '18614', chassis = 'MS', edition_name = 'Avante Mk.II', release_type = 'Original', edition_type = 'original', release_year = 2006, release_date = '2006-06-24', notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '5a123617-c84c-5012-ab20-1a9d493259e0';

-- Beat Magnum -- Beat Magnum
update product_releases set item_number = '19421', chassis = 'Super TZ', edition_name = 'Beat Magnum', release_type = 'Original', edition_type = 'original', release_year = 1997, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Very Rare', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '7683c862-f484-5603-aa28-c76ae7453892';

-- Beat Magnum -- Beat Magnum Premium
update product_releases set item_number = '19444', chassis = 'AR', edition_name = 'Beat Magnum Premium', release_type = 'Premium', edition_type = 'premium', release_year = 2015, release_date = '2015-03-21', notes = NULL, discontinued = false, rarity = 'Uncommon', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'a49b33d9-9f2c-5333-9521-8a7c732995d2';

-- Buster Sonic -- Buster Sonic
update product_releases set item_number = '19423', chassis = 'Super TZ', edition_name = 'Buster Sonic', release_type = 'Original', edition_type = 'original', release_year = 1997, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '217fd7d2-2090-593c-bb7d-bef7ce1cf154';

-- Copperfang -- Copperfang
update product_releases set item_number = '18092', chassis = 'FM-A', edition_name = 'Copperfang', release_type = 'Original', edition_type = 'original', release_year = 2019, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '9058782c-0e3c-5a3d-9f9c-391365d3e81e';

-- Cyclone Magnum -- Cyclone Magnum
update product_releases set item_number = '19412', chassis = 'Super TZ', edition_name = 'Cyclone Magnum', release_type = 'Original', edition_type = 'original', release_year = 1996, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Rare', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'efd6902b-f080-5165-8a13-0375c1d32298';

-- Cyclone Magnum -- Cyclone Magnum Premium
update product_releases set item_number = '19440', chassis = 'AR', edition_name = 'Cyclone Magnum Premium', release_type = 'Premium', edition_type = 'premium', release_year = 2014, release_date = '2014-11-21', notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '85a3549a-d563-5dda-bc6d-bd1ac684601e';

-- Dash-01 Horizon -- Dash-01 Horizon
update product_releases set item_number = NULL, chassis = 'Super II', edition_name = 'Dash-01 Horizon', release_type = 'Original', edition_type = 'original', release_year = 2017, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = 'a0b042ac-7e6c-57f4-98a2-bd92e8e39f39';

-- Dash-1 Emperor -- Dash-1 Emperor (Type 3 Chassis)
update product_releases set item_number = '18025', chassis = 'Type 3', edition_name = 'Dash-1 Emperor (Type 3 Chassis)', release_type = 'Original', edition_type = 'original', release_year = 1990, release_date = NULL, notes = 'Original 1990 release on the Type 3 chassis.', discontinued = false, rarity = 'Very Rare', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '96adee91-eaec-5c73-9269-cf3875cfe02d';

-- Dash-1 Emperor -- Dash-1 Emperor Premium
update product_releases set item_number = '18069', chassis = 'Super II', edition_name = 'Dash-1 Emperor Premium', release_type = 'Premium', edition_type = 'premium', release_year = 2012, release_date = '2012-03-24', notes = NULL, discontinued = false, rarity = 'Uncommon', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'f576fa21-8e57-5fa0-953e-f468653e3767';

-- Dash-1 Emperor -- Dash-1 Emperor Premium (Black Special)
update product_releases set item_number = '95359', chassis = 'Super II', edition_name = 'Dash-1 Emperor Premium (Black Special)', release_type = 'Color Special', edition_type = 'color_special', release_year = 2015, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Rare', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '96babc1a-f153-59fa-b840-7ff68fb50f38';

-- Dash-1 Emperor -- Dash-1 Emperor 30th Anniversary
update product_releases set item_number = '92403', chassis = 'Super II', edition_name = 'Dash-1 Emperor 30th Anniversary', release_type = 'Anniversary Edition', edition_type = 'anniversary', release_year = 2018, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Rare', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = 'b7eeb76a-e117-59ae-b31c-b099368421af';

-- Dash-1 Emperor -- Dash-1 Emperor (2026 Reissue)
update product_releases set item_number = '18025', chassis = 'Type 3', edition_name = 'Dash-1 Emperor (2026 Reissue)', release_type = 'Reissue', edition_type = 'reissue', release_year = 2026, release_date = NULL, notes = 'Modern sealed reissue sharing the classic 18025 item number and Type 3 chassis.', discontinued = false, rarity = 'Common', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '79e32904-fe5d-5d30-bf54-8643ce4b42d3';

-- Dash-2 Burning Sun -- Dash-2 Burning Sun
update product_releases set item_number = '18015', chassis = 'Type 1', edition_name = 'Dash-2 Burning Sun', release_type = 'Original', edition_type = 'original', release_year = 1989, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '1d677e65-ca9c-5549-94c5-32e9b957b31a';

-- Dash-3 Shooting Star -- Dash-3 Shooting Star
update product_releases set item_number = '18019', chassis = 'Type 3', edition_name = 'Dash-3 Shooting Star', release_type = 'Original', edition_type = 'original', release_year = 1989, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '178ef6b8-594c-5cf4-8084-3c910576b29b';

-- Dash-4 Cannon Ball -- Dash-4 Cannon Ball
update product_releases set item_number = NULL, chassis = 'Type 3', edition_name = 'Dash-4 Cannon Ball', release_type = 'Original', edition_type = 'original', release_year = 1990, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = 'c63b8f4a-43f3-597b-82e5-f0e45bb45b7a';

-- DCR-01 -- DCR-01
update product_releases set item_number = '18646', chassis = 'MA', edition_name = 'DCR-01', release_type = 'Original', edition_type = 'original', release_year = 2018, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'd32c3468-4ce4-5968-ba4e-d1e47e30eb01';

-- Dyna-Hawk GX -- Dyna-Hawk GX
update product_releases set item_number = '19201', chassis = 'Super X', edition_name = 'Dyna-Hawk GX', release_type = 'Original', edition_type = 'original', release_year = 1998, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Very Rare', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '2af882f6-8c66-5508-9acd-2240aac287ad';

-- Dyna-Hawk GX -- Dyna-Hawk GX Super XX Special
update product_releases set item_number = '94717', chassis = 'Super XX', edition_name = 'Dyna-Hawk GX Super XX Special', release_type = 'Color Special', edition_type = 'color_special', release_year = 2010, release_date = '2010-03-13', notes = NULL, discontinued = false, rarity = 'Rare', verification_status = 'partial', production_status = 'unknown', status_checked_at = NULL where id = '1ede5023-9035-5342-b207-6242c5f5190a';

-- Emperor (Premium Black Special) -- Emperor (Premium Black Special)
update product_releases set item_number = '18717', chassis = 'AR', edition_name = 'Emperor (Premium Black Special)', release_type = 'Limited Edition', edition_type = 'original', release_year = 2017, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '8c923a15-a5e7-5e5c-ab8f-b2d1f722ac76';

-- Festa Jaune -- Festa Jaune
update product_releases set item_number = '18637', chassis = 'MA', edition_name = 'Festa Jaune', release_type = 'Original', edition_type = 'original', release_year = 2014, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'cbd6e611-e421-5c10-bbd3-352beb80f6fc';

-- Fire Dragon -- Fire Dragon
update product_releases set item_number = '19414', chassis = 'Super 1', edition_name = 'Fire Dragon', release_type = 'Original', edition_type = 'original', release_year = 1992, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Rare', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '0e24ff2a-70e6-5909-b28d-67400a365c92';

-- Fire Dragon -- Fire Dragon Premium
update product_releases set item_number = '19414', chassis = 'Super 1', edition_name = 'Fire Dragon Premium', release_type = 'Premium', edition_type = 'premium', release_year = 2017, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = 'daf1d532-80b5-524f-896e-fb577dae2445';

-- Geo Glider -- Geo Glider
update product_releases set item_number = '18716', chassis = 'FM-A', edition_name = 'Geo Glider', release_type = 'Original', edition_type = 'original', release_year = 2018, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'a9a18e0d-7aa2-5481-94b6-ebc670daaa55';

-- Great Emperor -- Great Emperor
update product_releases set item_number = '18036', chassis = 'Type 3', edition_name = 'Great Emperor', release_type = 'Original', edition_type = 'original', release_year = 1990, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Grail', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '8c2ca80b-8a9d-5b7a-9325-aec13a0db9ba';

-- Great Emperor -- Great Emperor Premium
update product_releases set item_number = '18075', chassis = 'Super II', edition_name = 'Great Emperor Premium', release_type = 'Premium', edition_type = 'premium', release_year = 2015, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Rare', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '532f8e3a-f55f-5936-abcd-58e0f8538785';

-- Hurricane Sonic -- Hurricane Sonic
update product_releases set item_number = '19415', chassis = 'Super TZ', edition_name = 'Hurricane Sonic', release_type = 'Original', edition_type = 'original', release_year = 1996, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Rare', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '71addadb-04b3-579f-96f2-c5e976cf1cd5';

-- Hurricane Sonic -- Hurricane Sonic Premium
update product_releases set item_number = '19441', chassis = 'AR', edition_name = 'Hurricane Sonic Premium', release_type = 'Premium', edition_type = 'premium', release_year = 2014, release_date = '2014-11-21', notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'e1b626f8-e0ea-52c9-86f0-eb870561d70d';

-- Mad Bull -- Mad Bull
update product_releases set item_number = NULL, chassis = 'Super II', edition_name = 'Mad Bull', release_type = 'Original', edition_type = 'original', release_year = 1998, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Uncommon', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '454a8d07-e963-5699-9a8c-2151917f75a5';

-- Mad Bull -- Mad Bull (2013 Reissue)
update product_releases set item_number = NULL, chassis = 'Super II', edition_name = 'Mad Bull (2013 Reissue)', release_type = 'Reissue', edition_type = 'reissue', release_year = 2013, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = 'eb3b81bb-3a11-56af-a0cf-b625a1501434';

-- Magnum Saber -- Magnum Saber
update product_releases set item_number = '19401', chassis = 'Super 1', edition_name = 'Magnum Saber', release_type = 'Original', edition_type = 'original', release_year = 1994, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Very Rare', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '4a1b7d1f-a2f7-5113-9962-21fa14a47968';

-- Magnum Saber -- Magnum Saber Premium
update product_releases set item_number = '19431', chassis = 'Super II', edition_name = 'Magnum Saber Premium', release_type = 'Premium', edition_type = 'premium', release_year = 2012, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Uncommon', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '0fdbfd56-f257-5b84-b541-e08a7450cc34';

-- Manta Ray -- Manta Ray
update product_releases set item_number = '19413', chassis = 'Super 1', edition_name = 'Manta Ray', release_type = 'Original', edition_type = 'original', release_year = 1991, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Rare', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = 'b86d459a-bd44-5c68-b104-9ca4cedaf413';

-- Manta Ray -- Manta Ray (2015 Reissue)
update product_releases set item_number = '19413', chassis = 'Super 1', edition_name = 'Manta Ray (2015 Reissue)', release_type = 'Reissue', edition_type = 'reissue', release_year = 2015, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '5277616b-91d3-5f0c-b893-d77778beaf95';

-- Neo-Tridagger ZMC -- Neo-Tridagger ZMC
update product_releases set item_number = '19409', chassis = 'Super 1', edition_name = 'Neo-Tridagger ZMC', release_type = 'Original', edition_type = 'original', release_year = 1998, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Very Rare', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'fcaf3f82-93b5-5a52-8087-c96e771a030c';

-- Neo-Tridagger ZMC -- Neo-Tridagger ZMC (Premium)
update product_releases set item_number = NULL, chassis = 'Super II', edition_name = 'Neo-Tridagger ZMC (Premium)', release_type = 'Premium', edition_type = 'premium', release_year = 2016, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Uncommon', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '73dcd8e6-82ab-54c4-961b-f4132bf6d638';

-- Proto Emperor ZX -- Proto Emperor ZX
update product_releases set item_number = '18038', chassis = 'Super II', edition_name = 'Proto Emperor ZX', release_type = 'Original', edition_type = 'original', release_year = 2016, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '4d5b0a9a-498f-51fc-accd-9316ca11c843';

-- Proto Emperor ZX -- Proto Emperor ZX Premium (Black Special)
update product_releases set item_number = '95450', chassis = 'Super II', edition_name = 'Proto Emperor ZX Premium (Black Special)', release_type = 'Color Special', edition_type = 'color_special', release_year = 2019, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Very Rare', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'f0614cb8-d0cb-521d-aa2c-4fc304f39430';

-- Raikiri -- Raikiri
update product_releases set item_number = '18640', chassis = 'MA', edition_name = 'Raikiri', release_type = 'Original', edition_type = 'original', release_year = 2014, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '9a415521-3094-5724-a26b-e42a2c0148fa';

-- Raikiri -- Raikiri Black Special
update product_releases set item_number = '18640', chassis = 'MA', edition_name = 'Raikiri Black Special', release_type = 'Color Special', edition_type = 'color_special', release_year = 2016, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Uncommon', verification_status = 'partial', production_status = 'unknown', status_checked_at = NULL where id = '5addae7a-e863-5cfe-8231-7af05fcfcbb6';

-- Shadow Shark -- Shadow Shark
update product_releases set item_number = '18704', chassis = 'AR', edition_name = 'Shadow Shark', release_type = 'Original', edition_type = 'original', release_year = 2020, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'b57fbc18-d57c-5b3c-9def-ffb4e70c9e27';

-- Sonic Saber -- Sonic Saber
update product_releases set item_number = '19402', chassis = 'Super 1', edition_name = 'Sonic Saber', release_type = 'Original', edition_type = 'original', release_year = 1994, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Very Rare', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = 'e23951fd-63a5-5233-8c53-969c57e98819';

-- Sonic Saber -- Sonic Saber Premium
update product_releases set item_number = '19432', chassis = 'Super II', edition_name = 'Sonic Saber Premium', release_type = 'Premium', edition_type = 'premium', release_year = 2011, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Uncommon', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '62cca367-8a73-5280-b2a2-0aa9497d093d';

-- Super Avante -- Super Avante
update product_releases set item_number = '18101', chassis = 'VZ', edition_name = 'Super Avante', release_type = 'Original', edition_type = 'original', release_year = 2020, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '5e5251c2-a130-5fb0-93a7-2bd73c63736d';

-- Sword Flash -- Sword Flash
update product_releases set item_number = '18091', chassis = 'VZ', edition_name = 'Sword Flash', release_type = 'Original', edition_type = 'original', release_year = 2020, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '2a5e1b1b-07e8-57fa-a202-0b38982b168e';

-- Thunder Shot -- Thunder Shot (Type 3)
update product_releases set item_number = NULL, chassis = 'Type 3', edition_name = 'Thunder Shot (Type 3)', release_type = 'Original', edition_type = 'original', release_year = 1988, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Very Rare', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = 'dcaa9d00-fe3f-5bc4-9bfa-5bc1078e2087';

-- Thunder Shot -- Thunder Shot Premium
update product_releases set item_number = NULL, chassis = 'Super II', edition_name = 'Thunder Shot Premium', release_type = 'Premium', edition_type = 'premium', release_year = 2015, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Uncommon', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = 'f4e3f6b8-8ce6-5b87-9d94-5f64a24c031a';

-- Trigale -- Trigale
update product_releases set item_number = '18638', chassis = 'AR', edition_name = 'Trigale', release_type = 'Original', edition_type = 'original', release_year = 2015, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '08b3cc73-8c45-5ddd-bab4-9167c7f93c41';

-- Vanguard Sonic -- Vanguard Sonic
update product_releases set item_number = '19407', chassis = 'Super 1', edition_name = 'Vanguard Sonic', release_type = 'Original', edition_type = 'original', release_year = 1995, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Rare', verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '203f1f0f-1f5d-5e3b-bd56-b1a175f3e121';

-- Vanguard Sonic -- Vanguard Sonic (Super II)
update product_releases set item_number = '19435', chassis = 'Super II', edition_name = 'Vanguard Sonic (Super II)', release_type = 'Reissue', edition_type = 'reissue', release_year = 2013, release_date = NULL, notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = 'b3639c7d-581e-5da8-9ec4-ea1eb9d61193';

-- Victory Magnum -- Victory Magnum
update product_releases set item_number = '19406', chassis = 'Super 1', edition_name = 'Victory Magnum', release_type = 'Original', edition_type = 'original', release_year = 1995, release_date = NULL, notes = NULL, discontinued = false, rarity = 'Rare', verification_status = 'unverified', production_status = 'unknown', status_checked_at = NULL where id = '6ed25d50-4099-5924-b7e5-d7a21945a3f6';

-- Victory Magnum -- Victory Magnum Premium
update product_releases set item_number = '19434', chassis = 'Super II', edition_name = 'Victory Magnum Premium', release_type = 'Premium', edition_type = 'premium', release_year = 2011, release_date = '2011-06-25', notes = NULL, discontinued = false, rarity = NULL, verification_status = 'verified', production_status = 'unknown', status_checked_at = NULL where id = '0bdb9bcd-e4aa-53ab-b004-984cae96fdca';


-- =========================================================================
-- 4. Genuinely NEW releases (no already-deployed row) -- INSERT with
--    on conflict (id) do nothing for idempotency.
--    2 new release row(s).
-- =========================================================================

insert into product_releases (id, product_id, item_number, release_type, edition_type, edition_name, release_year, release_date, chassis, barcode_jan, color, country_market, msrp_jpy, msrp_eur, notes, discontinued, is_original, rarity, data_source, verification_status, production_status, status_checked_at) values
  ('45f04c74-a41c-5514-87a2-ab47ea6d66b6', '3b443635-b33f-5553-a39d-eba8b8cafddb', '18026', 'Reissue', 'reissue', 'Dash-2 Burning Sun (Type 3 Chassis)', 1990, NULL, 'Type 3', NULL, NULL, 'Japan', NULL, NULL, NULL, false, false, 'Very Rare', 'manual', 'verified', 'unknown', NULL),
  ('ace0d1b1-aaf3-589a-977c-a3df07c83c73', 'd3b4ad34-05ac-592e-ad93-fab4cfde0a5a', '95467', 'Reissue', 'reissue', 'Dyna-Hawk GX Super XX Special (2019 Reissue)', 2019, '2019-03-16', 'Super XX', NULL, NULL, 'Japan', NULL, NULL, NULL, false, false, 'Uncommon', 'manual', 'verified', 'unknown', NULL)
on conflict (id) do nothing;

-- Dash-2 Burning Sun -- Dash-2 Burning Sun (Type 3 Chassis) (item 18026)
-- Dyna-Hawk GX -- Dyna-Hawk GX Super XX Special (2019 Reissue) (item 95467)

-- =========================================================================
-- 5. canonical_release_id -- the release considered authoritative for
--    each product's identity. UNKNOWN > INVENTED: only set where a
--    release could be confidently identified as canonical (this
--    catalog's own `isOriginal` flag); never forced.
--    36 product row(s).
-- =========================================================================

-- Aero Avante
update products set canonical_release_id = 'a2baec17-32b5-5ca7-996b-4cdc2da725ba' where id = 'c8132bd5-23ee-5f36-b3f6-a75ef0c27ea3';

-- Aero Avante Japan Cup 2013
update products set canonical_release_id = '035abf4d-65da-5b0c-855d-9e611798c4e4' where id = '07cc02e9-2626-5a60-92fb-2c2ed2402d7f';

-- Astute
update products set canonical_release_id = '3d1c1580-c921-530f-9aaf-7ca5ff77e86c' where id = 'be48e786-11c6-567f-b063-8026957bb403';

-- Avante
update products set canonical_release_id = 'cafbb6ca-1aba-5732-946d-0045d054aa5c' where id = '82b478fd-21dd-5c93-82fb-bf50461a107d';

-- Avante Mk.II
update products set canonical_release_id = '5a123617-c84c-5012-ab20-1a9d493259e0' where id = '6dcb6511-5277-561f-a880-95ef828ce44f';

-- Beat Magnum
update products set canonical_release_id = '7683c862-f484-5603-aa28-c76ae7453892' where id = 'a66d871c-00b1-56e5-9bc4-1621ea1729b2';

-- Buster Sonic
update products set canonical_release_id = '217fd7d2-2090-593c-bb7d-bef7ce1cf154' where id = 'da28c703-24ef-5ebd-a952-87346735dc7e';

-- Copperfang
update products set canonical_release_id = '9058782c-0e3c-5a3d-9f9c-391365d3e81e' where id = 'e2f47ba4-03f1-5adb-8252-471c76729292';

-- Cyclone Magnum
update products set canonical_release_id = 'efd6902b-f080-5165-8a13-0375c1d32298' where id = '53791485-2948-5176-8acb-2ec947eafc51';

-- Dash-01 Horizon
update products set canonical_release_id = 'a0b042ac-7e6c-57f4-98a2-bd92e8e39f39' where id = '813a9ba0-170e-5636-9a9a-a7e7fca32366';

-- Dash-1 Emperor
update products set canonical_release_id = '96adee91-eaec-5c73-9269-cf3875cfe02d' where id = '2972e27d-7c75-5534-9ed4-1603ef4a6655';

-- Dash-2 Burning Sun
update products set canonical_release_id = '1d677e65-ca9c-5549-94c5-32e9b957b31a' where id = '3b443635-b33f-5553-a39d-eba8b8cafddb';

-- Dash-3 Shooting Star
update products set canonical_release_id = '178ef6b8-594c-5cf4-8084-3c910576b29b' where id = '4b53383c-c417-53c6-addb-e87126546d89';

-- Dash-4 Cannon Ball
update products set canonical_release_id = 'c63b8f4a-43f3-597b-82e5-f0e45bb45b7a' where id = 'd2c3e3d8-050d-5b9b-932f-023f2ee7dce2';

-- DCR-01
update products set canonical_release_id = 'd32c3468-4ce4-5968-ba4e-d1e47e30eb01' where id = 'd341ec22-c1f9-5a03-906d-444f8eee5401';

-- Dyna-Hawk GX
update products set canonical_release_id = '2af882f6-8c66-5508-9acd-2240aac287ad' where id = 'd3b4ad34-05ac-592e-ad93-fab4cfde0a5a';

-- Emperor (Premium Black Special)
update products set canonical_release_id = '8c923a15-a5e7-5e5c-ab8f-b2d1f722ac76' where id = '6d6174e7-4040-5035-a3a4-cede97265d38';

-- Festa Jaune
update products set canonical_release_id = 'cbd6e611-e421-5c10-bbd3-352beb80f6fc' where id = '51deac9c-f8a7-5eff-984f-968d6ad88659';

-- Fire Dragon
update products set canonical_release_id = '0e24ff2a-70e6-5909-b28d-67400a365c92' where id = '65c7f3e3-ebfc-55a6-8855-c0c495164b72';

-- Geo Glider
update products set canonical_release_id = 'a9a18e0d-7aa2-5481-94b6-ebc670daaa55' where id = '68acb096-f01b-55b2-949b-a959279a2fa5';

-- Great Emperor
update products set canonical_release_id = '8c2ca80b-8a9d-5b7a-9325-aec13a0db9ba' where id = '203f8219-9d37-5a1a-aad6-9437c80a1ea8';

-- Hurricane Sonic
update products set canonical_release_id = '71addadb-04b3-579f-96f2-c5e976cf1cd5' where id = 'dee35418-283b-5603-889b-b3eb2d68eea5';

-- Mad Bull
update products set canonical_release_id = '454a8d07-e963-5699-9a8c-2151917f75a5' where id = '643f208f-c8f6-5574-b9cf-565e28602d17';

-- Magnum Saber
update products set canonical_release_id = '4a1b7d1f-a2f7-5113-9962-21fa14a47968' where id = 'fa551244-1a12-54ec-b937-ad1b5603e8bb';

-- Manta Ray
update products set canonical_release_id = 'b86d459a-bd44-5c68-b104-9ca4cedaf413' where id = '0b2e1cf8-6c19-5342-89ef-6a53b3f51af3';

-- Neo-Tridagger ZMC
update products set canonical_release_id = 'fcaf3f82-93b5-5a52-8087-c96e771a030c' where id = '9793fbe8-dcf7-51c9-9f45-185194a0bc92';

-- Proto Emperor ZX
update products set canonical_release_id = '4d5b0a9a-498f-51fc-accd-9316ca11c843' where id = 'a1fd4f6d-0834-5f09-ac3c-5d4b398f0968';

-- Raikiri
update products set canonical_release_id = '9a415521-3094-5724-a26b-e42a2c0148fa' where id = 'c7a440cc-dc07-5ecc-bae3-c2770dc8b66e';

-- Shadow Shark
update products set canonical_release_id = 'b57fbc18-d57c-5b3c-9def-ffb4e70c9e27' where id = '6f41e40f-a48e-509f-8602-dfd303e25795';

-- Sonic Saber
update products set canonical_release_id = 'e23951fd-63a5-5233-8c53-969c57e98819' where id = '896cc70e-3048-594d-9389-cb9808a5ad53';

-- Super Avante
update products set canonical_release_id = '5e5251c2-a130-5fb0-93a7-2bd73c63736d' where id = 'dcd372ac-5ad2-5a70-ae48-f1c4a6d6de4a';

-- Sword Flash
update products set canonical_release_id = '2a5e1b1b-07e8-57fa-a202-0b38982b168e' where id = '5b415a05-bc7c-589c-8b9c-3b3806479f6b';

-- Thunder Shot
update products set canonical_release_id = 'dcaa9d00-fe3f-5bc4-9bfa-5bc1078e2087' where id = '059b5b3f-9ee9-5932-b39f-879642b9414c';

-- Trigale
update products set canonical_release_id = '08b3cc73-8c45-5ddd-bab4-9167c7f93c41' where id = 'b972592b-ce68-5f39-b3a1-cdc8984d3817';

-- Vanguard Sonic
update products set canonical_release_id = '203f1f0f-1f5d-5e3b-bd56-b1a175f3e121' where id = 'a00d2b12-6a67-56ee-8db5-392eaf86d5c7';

-- Victory Magnum
update products set canonical_release_id = '6ed25d50-4099-5924-b7e5-d7a21945a3f6' where id = 'f603ed6f-e601-5372-9fe7-6fd1034b6065';


-- =========================================================================
-- 6. release_sources -- provenance for releases with a documented
--    official source (from the catalog integrity audit, not new
--    research). Not exhaustive: a release with no source recorded here
--    is valid and common, not an error -- see docs/CATALOG_MODEL_V2.md
--    section 13.
--    38 source row(s) across 36 release(s).
-- =========================================================================

insert into release_sources (id, release_id, source_type, source_url, verified_fields, checked_at, notes) values
  ('4c0e7687-ff22-514b-8761-b4b4b9aef51f', 'a2baec17-32b5-5ca7-996b-4cdc2da725ba', 'official_manufacturer', 'https://www.tamiya.com/english/products/18701/index.html', '{"itemNumber","chassis"}'::text[], '2026-09-03', NULL),
  ('671f1490-fe87-5e8d-8ed9-1b5bcbce24ab', 'cafbb6ca-1aba-5732-946d-0045d054aa5c', 'official_manufacturer', 'https://www.tamiya.com/japan/products/18014/index.html', '{"itemNumber"}'::text[], '2026-09-04', NULL),
  ('d62212f5-04b5-539b-b9ce-e21575a890df', '5a123617-c84c-5012-ab20-1a9d493259e0', 'official_manufacturer', 'https://www.tamiya.com/english/products/18614/index.html', '{"itemNumber","chassis","releaseDate"}'::text[], '2026-09-03', NULL),
  ('58af2490-9f65-559d-8fba-1ac1a6295f65', '7683c862-f484-5603-aa28-c76ae7453892', 'official_manufacturer', 'https://www.tamiya.com/japan/products/19421/index.html', '{"itemNumber"}'::text[], '2026-09-04', NULL),
  ('54dd7a1b-e2d7-5b78-b408-5edc3c28a56d', 'a49b33d9-9f2c-5333-9521-8a7c732995d2', 'official_manufacturer', 'https://www.tamiya.com/japan/products/19444/index.html', '{"itemNumber","chassis","releaseDate"}'::text[], '2026-09-04', NULL),
  ('2250d106-d765-5f5b-8661-3af207b806ad', '217fd7d2-2090-593c-bb7d-bef7ce1cf154', 'official_manufacturer', 'https://www.tamiya.com/japan/products/19423/index.html', '{"itemNumber"}'::text[], '2026-09-04', NULL),
  ('eda70c1d-8831-5fe5-b0fb-53876348c888', 'efd6902b-f080-5165-8a13-0375c1d32298', 'official_manufacturer', 'https://www.tamiya.com/japan/products/19412/index.html', '{"itemNumber"}'::text[], '2026-09-04', NULL),
  ('7ce6ef62-4f3e-553f-8e0e-a43e261d99ee', '85a3549a-d563-5dda-bc6d-bd1ac684601e', 'official_manufacturer', 'https://www.tamiya.com/japan/products/19440/index.html', '{"itemNumber","chassis","releaseDate"}'::text[], '2026-09-04', NULL),
  ('96b6561a-755b-5c8f-819c-64f2223b055d', '96adee91-eaec-5c73-9269-cf3875cfe02d', 'official_manufacturer', 'https://www.tamiya.com/japan/products/18025/index.html', '{"itemNumber","chassis","releaseYear"}'::text[], '2026-09-04', NULL),
  ('2760c74d-b280-522a-af95-1cab4edeeda1', 'f576fa21-8e57-5fa0-953e-f468653e3767', 'official_manufacturer', 'https://www.tamiya.com/japan/products/18069/index.html', '{"itemNumber","chassis","releaseDate"}'::text[], '2026-09-04', NULL),
  ('ee4c98fd-eb62-5c84-8154-ae9bb32af28e', '79e32904-fe5d-5d30-bf54-8643ce4b42d3', 'official_manufacturer', 'https://www.tamiya.com/english/products/18025/index.html', '{"chassis"}'::text[], '2026-06-24', 'Page explicitly dated ''current as of June 24, 2026''; confirms the 2026 reissue is still Type 3 chassis, not Super-II.'),
  ('e5042c82-3b36-58c5-a779-ae3ed384c896', '1d677e65-ca9c-5549-94c5-32e9b957b31a', 'official_manufacturer', 'https://www.tamiya.com/japan/products/18015/index.html', '{"itemNumber","chassis","releaseYear"}'::text[], '2026-09-04', NULL),
  ('d5fb20f2-3c61-5b26-b886-67af9fd235cc', '45f04c74-a41c-5514-87a2-ab47ea6d66b6', 'official_manufacturer', 'https://www.tamiya.com/japan/products/18026/index.html', '{"itemNumber","chassis","releaseYear"}'::text[], '2026-09-04', NULL),
  ('b528ec02-bdae-5e41-a4de-d363dabc1045', '178ef6b8-594c-5cf4-8084-3c910576b29b', 'official_manufacturer', 'https://www.tamiya.com/japan/products/18019/index.html', '{"itemNumber","chassis","releaseYear"}'::text[], '2026-09-04', NULL),
  ('8f5eb0a2-041d-54ea-b85b-fd18b6db59ef', 'd32c3468-4ce4-5968-ba4e-d1e47e30eb01', 'official_manufacturer', 'https://www.tamiya.com/english/products/18646/index.html', '{"itemNumber"}'::text[], '2026-09-03', NULL),
  ('4fbcbf8d-f9fb-5e0d-b008-b7d85535366f', '2af882f6-8c66-5508-9acd-2240aac287ad', 'official_manufacturer', 'https://www.tamiya.com/japan/products/19201/index.html', '{"itemNumber"}'::text[], '2026-09-04', NULL),
  ('8f4630c9-961b-5ea9-a35e-2324905e2b54', 'ace0d1b1-aaf3-589a-977c-a3df07c83c73', 'official_manufacturer', 'https://www.tamiya.com/japan/products/95467/index.html', '{"itemNumber","chassis","releaseDate"}'::text[], '2026-09-04', NULL),
  ('bf212ae7-e289-5635-a676-7fc056814f57', 'cbd6e611-e421-5c10-bbd3-352beb80f6fc', 'official_catalog_pdf', 'https://www.tamiyausa.com/media/files/map-price-list-jan-2019-969-c5cb.pdf', '{"itemNumber"}'::text[], '2026-09-04', 'Official Tamiya America MAP price list PDF -- confirms this catalog''s OLD (wrong) item was really ''Shooting Proud Star''.'),
  ('2ce5ea0e-6962-5d4c-9a70-2e844b2a7c25', 'cbd6e611-e421-5c10-bbd3-352beb80f6fc', 'official_manufacturer', 'https://tamiya.com/english/products/18637/index.html', '{"itemNumber","chassis"}'::text[], '2026-09-04', NULL),
  ('1fde9807-0ed5-5495-8040-557366f2d646', 'a9a18e0d-7aa2-5481-94b6-ebc670daaa55', 'official_manufacturer', 'https://www.tamiya.com/english/products/18716/index.html', '{"itemNumber","releaseYear"}'::text[], '2026-09-03', NULL),
  ('580f6156-bede-5d31-8d01-05f797a8a344', '8c2ca80b-8a9d-5b7a-9325-aec13a0db9ba', 'official_manufacturer', 'https://www.tamiya.com/japan/products/18036/index.html', '{"itemNumber"}'::text[], '2026-09-04', NULL),
  ('251fbc69-8d99-5e47-bad1-86be7bcf1cec', '532f8e3a-f55f-5936-abcd-58e0f8538785', 'official_manufacturer', 'https://www.tamiya.com/japan/products/18075/index.html', '{"itemNumber","chassis"}'::text[], '2026-09-04', NULL),
  ('008b91e5-ea18-5f70-b5bf-61586fd1bb52', '71addadb-04b3-579f-96f2-c5e976cf1cd5', 'official_manufacturer', 'https://www.tamiya.com/japan/products/19415/index.html', '{"itemNumber"}'::text[], '2026-09-04', NULL),
  ('f75311f9-ee64-56a1-8c61-f686f278484f', 'e1b626f8-e0ea-52c9-86f0-eb870561d70d', 'official_manufacturer', 'https://www.tamiya.com/japan/products/19441/index.html', '{"itemNumber","chassis","releaseDate"}'::text[], '2026-09-04', NULL),
  ('6cdfe0e6-05a3-5721-bb26-e7b347924fb0', '454a8d07-e963-5699-9a8c-2151917f75a5', 'official_manufacturer', 'https://www.tamiya.com/japan/products/18615/index.html', '{"itemNumber"}'::text[], '2026-09-04', 'Confirms item 18615 is really Manta Ray Mk.II, not this product -- source for why the item was cleared to NULL.'),
  ('c96ff338-6595-5501-9ac4-a4074139ba3f', '0fdbfd56-f257-5b84-b541-e08a7450cc34', 'official_manufacturer', 'https://www.tamiya.com/english/products/19431/index.html', '{"itemNumber","chassis"}'::text[], '2026-09-03', NULL),
  ('228c6838-37e1-5ac0-a6f1-734d304c8422', 'fcaf3f82-93b5-5a52-8087-c96e771a030c', 'official_manufacturer', 'https://www.tamiya.com/japan/products/19409/index.html', '{"itemNumber","chassis"}'::text[], '2026-09-04', NULL),
  ('81682ed7-0173-52fb-8e03-3dcd1853750c', '4d5b0a9a-498f-51fc-accd-9316ca11c843', 'official_manufacturer', 'https://www.tamiya.com/japan/products/18038/index.html', '{"itemNumber","releaseDate"}'::text[], '2026-09-04', NULL),
  ('dd2218b0-2adc-51a9-8cba-d540e6c8212a', 'f0614cb8-d0cb-521d-aa2c-4fc304f39430', 'official_manufacturer', 'https://www.tamiya.com/japan/products/95450/index.html', '{"itemNumber","chassis"}'::text[], '2026-09-04', NULL),
  ('d233ba0a-bf54-593c-944b-ac5eaad6d111', '9a415521-3094-5724-a26b-e42a2c0148fa', 'official_manufacturer', 'https://www.tamiya.com/english/products/18640/index.html', '{"itemNumber","chassis"}'::text[], '2026-09-03', NULL),
  ('06bb2cf7-df55-5c1e-9e79-a91071db9036', 'b57fbc18-d57c-5b3c-9def-ffb4e70c9e27', 'official_manufacturer', 'https://www.tamiya.com/english/products/18704/index.html', '{"itemNumber","chassis"}'::text[], '2026-09-03', NULL),
  ('b73d7d5e-ff41-53d7-a640-d3ab67309332', '62cca367-8a73-5280-b2a2-0aa9497d093d', 'official_manufacturer', 'https://www.tamiya.com/english/products/19432/index.html', '{"itemNumber","chassis"}'::text[], '2026-09-04', NULL),
  ('d20c425a-3ed4-55d6-812e-f8a2d92d38b7', '5e5251c2-a130-5fb0-93a7-2bd73c63736d', 'official_manufacturer', 'https://www.tamiya.com/english/products/18101/index.html', '{"itemNumber"}'::text[], '2026-09-03', NULL),
  ('a0dc62e4-7c31-5eac-b5b9-dac01fa02925', '08b3cc73-8c45-5ddd-bab4-9167c7f93c41', 'official_catalog_pdf', 'https://www.tamiyausa.com/media/files/map-price-list-jan-2019-969-c5cb.pdf', '{"itemNumber"}'::text[], '2026-09-04', '''Tri Gale'' consistently listed as item 18638 across multiple official Tamiya America MAP price list PDFs.'),
  ('9cd8c2bb-60d5-5599-8688-bac7d9cecb63', '203f1f0f-1f5d-5e3b-bd56-b1a175f3e121', 'official_manufacturer', 'https://www.tamiya.com/japan/products/19407/index.html', '{"itemNumber"}'::text[], '2026-09-04', NULL),
  ('536c30d2-d08f-52b2-82e0-6b37574c4e48', 'b3639c7d-581e-5da8-9ec4-ea1eb9d61193', 'official_manufacturer', 'https://www.tamiya.com/english/products/19435/index.html', '{"itemNumber","chassis"}'::text[], '2026-09-04', NULL),
  ('a1afb374-5812-5650-bfbb-d1974a527bf4', '0bdb9bcd-e4aa-53ab-b004-984cae96fdca', 'official_manufacturer', 'https://www.tamiya.com/english/products/19434/index.html', '{"itemNumber","chassis","releaseDate"}'::text[], '2026-09-04', NULL),
  ('33ac3408-eae1-5716-93ff-6241f594896d', '0bdb9bcd-e4aa-53ab-b004-984cae96fdca', 'official_manufacturer', 'https://www.tamiya.com/japan/products/19434/index.html', '{"itemNumber","chassis","releaseDate"}'::text[], '2026-09-04', NULL)
on conflict (id) do nothing;