-- TrackDash global starting-offer semantics correction — 2026-09-24
--
-- "Disponibile da" must represent the lowest valid current acquisition cost
-- among Europe-comparable offers after canonical matching/deduplication.
-- The runtime fix changes only starting-offer selection; Market Value logic is
-- intentionally unchanged.
--
-- Recompute every signal that currently exposes active/current offer evidence
-- so persisted starting_* fields are regenerated by the canonical worker after
-- the corrected runtime is deployed.

select public.trackdash_enqueue_market_recompute(
  s.release_id,
  s.condition
)
from public.market_release_signals s
where coalesce(s.current_offer_count, 0) > 0
   or coalesce(s.active_offer_count, 0) > 0
   or s.starting_effective_cost_eur is not null
   or s.starting_item_price_eur is not null;
